spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect